version: "3.9"

services:

  hippocooking_db:
    image: mysql:8.0
    container_name: hippocooking_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - wordpress_network

  hippocooking_wordpress:
    image: wordpress:latest
    container_name: hippocooking_wordpress
    restart: always
    expose:
      - 80
    depends_on:
      - hippocooking_db
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
    networks:
      - wordpress_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-dhparams:/etc/ssl/certs
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done'"
    networks:
      - wordpress_network


  hippocooking_nginx_web_server:
    build: ./nginx
    container_name: hippocooking_nginx_web_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_web_server/nginx_errors:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-dhparams:/etc/ssl/certs
    depends_on:
      - hippocooking_wordpress
    networks:
      - wordpress_network


#Docker Networks
networks:
  wordpress_network:
    driver: bridge