version: "3.7"

services:

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - u-online

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    expose:
      - 80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
    networks:
      - u-online


  nginx_web_server:
    build: ./nginx
    container_name: nginx_web_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_web_server/nginx_errors:/var/log/nginx
      - /etc/ssl:/etc/ssl # dhparams file
      - /etc/letsencrypt/live:/etc/letsencrypt/live # current certificate
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive # all certificates (symlinks from /live points here)
      - /etc/letsencrypt/wk:/etc/letsencrypt/wk # folder where you have to put the brave reward token
    depends_on:
      - flask_webapp
      - wordpress
    networks:
      - u-online


#Docker Networks
networks:
  u-online:
    driver: bridge